Repository Nmbrs/tf-modules, pull requests merged in 2023-01, with the labels that each got.

#172 feat(cosmo_db): create new cosmo db module
  azure/cosmo_db/local.tf
  azure/cosmo_db/main.tf
  azure/cosmo_db/terraform.tf
  azure/cosmo_db/varaiables.tf
Labels: cpr:invalid

#173 refactor(cosmos_db): rename cosmos_db module
  azure/cosmos_db/local.tf
  azure/cosmos_db/main.tf
  azure/cosmos_db/terraform.tf
  azure/cosmos_db/varaiables.tf
Labels: review needed

#167 feat(environment): create environment module
  general/environment/README.md
  general/environment/outputs.tf
  general/environment/terraform.tf
  general/environment/variables.tf
Labels: review needed

#168 feat(location): create location module
  azure/location/README.md
  azure/location/main.tf
  azure/location/outputs.tf
  azure/location/terraform.tf
  azure/location/variables.tf
Labels: review needed

#170 feat(key_vault): remove environment validation
  azure/key_vault/README.md
  azure/key_vault/terraform.tf
  azure/key_vault/variables.tf
Labels: review needed

#171 feat(virtual_network): remove environment validation
  azure/virtual_network/README.md
  azure/virtual_network/terraform.tf
  azure/virtual_network/variables.tf
Labels: review needed

#174 feat(storage_account): remove tag logic
  azure/storage_account/README.md
  azure/storage_account/local.tf
  azure/storage_account/main.tf
  azure/storage_account/terraform.tf
  azure/storage_account/variables.tf
Labels: to merge

#175 feat(dns_zone): remove tag logic from terraform
  azure/dns_zone/README.md
  azure/dns_zone/main.tf
  azure/dns_zone/terraform.tf
  azure/dns_zone/variables.tf
Labels: to merge

#176 feat(nat_gateway): remove tag logic from terraform
  azure/nat_gateway/main.tf
  azure/nat_gateway/terraform.tf
Labels: to merge

#179 feat(dns_records): remove tag logic from terraform
  azure/dns_records/README.md
  azure/dns_records/local.tf
  azure/dns_records/main.tf
  azure/dns_records/outputs.tf
  azure/dns_records/terraform.tf
  azure/dns_records/variables.tf
Labels: to merge

#178 feat(virtual_network): remove tag logic from terraform
  azure/virtual_network/README.md
  azure/virtual_network/local.tf
  azure/virtual_network/main.tf
  azure/virtual_network/variables.tf
Labels: to merge
